#ifndef __RT_AI_MODEL_FULL_MODEL_H
#define __RT_AI_MODEL_FULL_MODEL_H

#include <model_full.h>
#include <model_full_data.h>

/* model info ... */

// model name
#define RT_AI_MODEL_FULL_MODEL_NAME			"model_full"
#define RT_AI_MODEL_FULL_WORK_BUFFER_BYTES		AI_MODEL_FULL_DATA_ACTIVATIONS_SIZE
#define RT_AI_MODEL_FULL_DATA_WEIGHTS_SIZE		AI_MODEL_FULL_DATA_WEIGHTS_SIZE

#define RT_AI_MODEL_FULL_BUFFER_ALIGNMENT		AI_MODEL_FULL_ACTIVATIONS_ALIGNMENT

#define RT_AI_MODEL_FULL_IN_NUM				AI_MODEL_FULL_IN_NUM
#define RT_AI_MODEL_FULL_IN_1_SIZE				AI_MODEL_FULL_IN_1_SIZE
#define RT_AI_MODEL_FULL_IN_1_SIZE_BYTES		AI_MODEL_FULL_IN_1_SIZE_BYTES
#define RT_AI_MODEL_FULL_IN_TOTAL_SIZE_BYTES	(AI_MODEL_FULL_IN_1_SIZE_BYTES)
#define RT_AI_MODEL_FULL_IN_SIZE_BYTES			{AI_MODEL_FULL_IN_1_SIZE_BYTES}


#define RT_AI_MODEL_FULL_OUT_NUM				AI_MODEL_FULL_OUT_NUM
#define RT_AI_MODEL_FULL_OUT_1_SIZE			AI_MODEL_FULL_OUT_1_SIZE
#define RT_AI_MODEL_FULL_OUT_1_SIZE_BYTES		AI_MODEL_FULL_OUT_1_SIZE_BYTES
#define RT_AI_MODEL_FULL_OUT_TOTAL_SIZE_BYTES	(AI_MODEL_FULL_OUT_1_SIZE_BYTES)
#define RT_AI_MODEL_FULL_OUT_SIZE_BYTES		{AI_MODEL_FULL_OUT_1_SIZE_BYTES}


#define RT_AI_MODEL_FULL_TOTAL_BUFFER_SIZE		(NULL)		//unused

#endif	//end
